### ISSUE TITLE
No redirection to secure site

### ISSUE THREAD

**Issue by vahtis** [biblepay/BiblePayPool#13]
Site is not redirecting to https by default.

**Comment by vahtis** [comment]
Here is screenshot 
![image](https://user-images.githubusercontent.com/10445226/51893374-57270480-23ad-11e9-9ca4-f5c85b2ff6ab.png)

**Comment by biblepay** [comment]
Implemented a fix.

Thanks.

**Comment by sunk818** [comment]
Referenced images also should be `https` not `http` as good practice.

> Mixed Content: The page at 'https://pool.biblepay.org/pool.ashx' was loaded over HTTPS, but requested an insecure image 'http://pool.biblepay.org/SAN/ab09e91e-507d-4e1b-99fd-5c45f0fa5443.png'. This content should also be served over HTTPS.

**Comment by biblepay** [comment]
HTTPS images fixed.
