### ISSUE TITLE
Cannot read already sent letters

### ISSUE THREAD

**Issue by vahtis** [biblepay/BiblePayPool#14]
I was trying to write a new letter, but at the moment I could not read already written letters

![image](https://user-images.githubusercontent.com/10445226/51895724-8b052880-23b3-11e9-9314-cdc1196487e8.png)

**Comment by biblepay** [comment]
Wow, I wonder where all that came from, must be those strict html fix rules we just added.

**Comment by biblepay** [comment]
Fixed, thanks for finding this!
