### ISSUE TITLE
Left nav only appearing, no login screen

### ISSUE THREAD

**Issue by sunk818** [biblepay/BiblePayPool#15]
If I go to pool.biblepay.org, only the left nav appears and nothing works. No login screen, none of the menu options work.

![image](https://user-images.githubusercontent.com/6989799/52020152-1f02ed00-24a5-11e9-8ce7-57f60fcc5b85.png)

Chrome console says:

> Access to XMLHttpRequest at 'https://pool.biblepay.org/pool.ashx' (redirected from 'http://pool.biblepay.org/pool.ashx') from origin 'http://pool.biblepay.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Going to `pool.ashx` brings up what I expect. [https://pool.biblepay.org/pool.ashx](https://pool.biblepay.org/pool.ashx)

**Comment by sunk818** [comment]
This is from SVK Noko:

![biblepay-pool](https://user-images.githubusercontent.com/6989799/52070278-54571b80-2535-11e9-8d02-1b513ad39ffa.png)

**Comment by biblepay** [comment]
Fixed.
