### ISSUE TITLE
WE NEED THIS INFORMATIN ON POOL 

### ISSUE THREAD

**Issue by canopussy** [biblepay/BiblePayPool#3]
Pool Efficiency
Current Active Workers
Current Difficulty
Est. Next Difficulty
Est. Avg. Time per Round (Network)
Est. Avg. Time per Round (Pool)
Est. Shares this Round
Next Network Block
Last Block Found
Time Since Last Block
etc.

**Comment by biblepay** [comment]
Implemented on About Page.
