### ISSUE TITLE
Modify Pool Proposal View to Pull in Proposals created outside of it

### ISSUE THREAD

**Issue by super-coding** [biblepay/BiblePayPool#6]
Right now the pool only shows proposals that were created using the pool, 
if a future user uses commands to create a proposal outside of the pool, 
their proposal will not show up in the pool proposal view. 

Potential Resource/Reference:

DASH Ninja
https://www.dashninja.pl/governance.html

Source Code:
https://github.com/elbereth/dashninja-fe
https://github.com/elbereth/dashninja-be
https://github.com/elbereth/dashninja-db
https://github.com/elbereth/dashninja-ctl

**Comment by biblepay** [comment]
Thanks - sorry for the delay - we finally did this last quarter.  Implemented.

Thanks,
Rob
