### ISSUE TITLE
Ecommerce Store Menu/Tab Missing?

### ISSUE THREAD

**Issue by super-coding** [biblepay/BiblePayPool#8]
https://twitter.com/BiblePay/status/937506435323387904
https://www.reddit.com/r/BiblePay/comments/76znp0/biblepay_store_ecommerce_idea/

I assume it is probably very lower priority right now, 
I think its really cool, look forward to seeing it back later on, just documenting for future.

**Comment by biblepay** [comment]
Thanks, I am really glad someone at least noticed!  Sorry for the delay.

The link will be back very soon.  We are now working to see if we can potentially integrate with WalMart.  So far the integration is promising.

If this goes as planned you should have the ability to buy subway gift cards from the pool (in BiblePay) within 45 days!  Im very excited about this personally.
